language: java

sudo: false

os:
  - linux
  - osx

jdk:
  - oraclejdk9
  - openjdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -U -V -f server/pom.xml

script:
  - mvn test -B -f server/pom.xml
